# @package _global_

fps: 30

env:
  name: kmanip
  task: KManipSoloArmVision
  state_dim: 10
  action_dim: 7
  fps: ${fps}
  episode_length: 64
  # gym:
  #   obs_type: pixels_agent_pos
  #   render_mode: rgb_array